### ISSUE TITLE
Domain and Repo with the same name collide

### ISSUE THREAD

**Issue by alexanderpolson** [walmsles/cdk-codeartifact#8]
When creating a domain and an associated repo of the same name, the ids collide. Doing this from the console is valid so it would be good to be consistent with that. This could be as simple as updating the ids used for the [CfnDomain](https://github.com/walmsles/cdk-codeartifact/blob/main/src/codeartifact.ts#L21) and [CfnRepository](https://github.com/walmsles/cdk-codeartifact/blob/main/src/codeartifact.ts#L29) L1 Constructs to be qualified. Something like "${domainName}CodeArtifactDomain" and "${repoName}CodeArtifactRepository", respectively.

It may be worthwhile to explore other L2 Constructs in the AWS CDK to see what sort of pattern is used there.

**Comment by walmsles** [comment]
Hi @alexanderpolson am researching around best practise here in the community for Constructs creating multiple resources in a loop to resolve this one - The error is related to CDK requirement of unique identifiers within a construct scope which translates to generation of names within the cloudformation stack file and CF Logical IDs.

Will be releasing a new major version since this introduces a breaking change for existing stacks.

**Comment by walmsles** [comment]
Resolved in release v1.0.1.  Have appended "-CfnDom" to the Id of the Domain and "-CfnRepo" to the Id of the Repositories which enables inserting of a new repository into an existing CDK stack without any side effects.
